### ISSUE TITLE
How to manually clear the cache?

### ISSUE THREAD

**Issue by jvallarvisp** [mattecapu/dataloader-sequelize-wrapper#3] opened 2016-12-09 06:12 UTC
Is there a way to clear the cache?

**Comment by mattecapu** [comment] 2016-12-10 08:45
Oh yeah, there's no way as of now but it should totally be possible... you may PR this or I will add it by myself the next week.

**Comment by mattecapu** [comment] 2016-12-11 13:43
Ok I'm sorry I didn't think this enough in the previous answer, but there's actually a way to clear the cache:
```js
let a = new Cache(orm);
// do stuff
// something invalidates cache? throw it away
a = new Cache(orm);
```
if you're careful (as you should always be), the old cache is now unreachable so it will be collected as soon as the next GC runs.

Clearing a single model cache is not allowed by design because the single model caches are all interlinked by relationships and clearing just one would leave the whole cache in an inconsistent state. Yes, you could do it anyway by invalidating each reference of the objects in the cache being cleared... but I don't think it's worth it.
I conceived the library as an immutable caching layer for my GraphQL API, so it never made sense for it to have mutation methods.

**Comment by jvallarvisp** [comment] 2016-12-13 08:25
Hi @mattecapu, thanks for your reply. I really like this wrapper and it fits to my need. About the clearing cache. I am not clearing all the cache information. For example, in my use case, I `user.load(1)` and user id = 1 will be query to the database and save to cache. And in the event that I have to update the information of that user. I want to hit the database again with the new updated data. and save it to cache.

after updating the user information in the database, I should clear the cache. The function could be like this:
```
cache.from('user').clear(updateUser.id)
```
then load it again somewhere
```
cache.from('user').load(updatedUser.id)
```

**Comment by mattecapu** [comment] 2016-12-13 08:51
Hi @jvallarvisp, thanks for using this library!
I wrote this library as a thin caching layer between Sequelize and my GraphQL front-end, so following [DataLoader](https://github.com/facebook/dataloader#using-with-graphql)'s own suggestions on this regard I used it as a short-lived cache which is flushed every request.
Are you using it differenly? (probably yes)
If yes, I might consider working a bit on it to allow invalidation and maybe remove the wrapper interface to DataLoader in order to allow more options (e.g. use a Redis backend).

**Comment by jvallarvisp** [comment] 2016-12-13 23:04
Hi @mattecapu, I am also using GraphQL, React, Apollo, Sequelize, MySQL and Meteor.
This is my sample code.

```
import {
    users,
    tickets,
    note,
    ticket_history,
} from './models/';

import {db, pool} from './sequelize_connection.js';
import {PubSub} from 'graphql-subscriptions'
const pubsub = new PubSub();

import Cache from 'dataloader-sequelize-wrapper';
const cache = new Cache(db);

const resolvers = {
     ticket_history: {
            users(ticket_history)  {
                return cache.from('users').load(ticket_history.users_id);
            }
           notes(ticket_history)  {
                return note.findAll({where:{id:ticket_history.note_id}});
            }
        },
        note: {
            users(note)  {
                  return cache.from('users').load(note.users_id);
        },
}
export {resolvers, pubsub};
```

I have also a mutation that updates user information. In the event that I have to hit that functions, I need to remove that user in the cache if it exist.

How to flushed the cache every request?

**Comment by mattecapu** [comment] 2016-12-14 11:52
I'm thinking of open-source a package to do that, but it would be a Koa/Express middleware (like I'm doing it now).
I don't know how Meteor handles the routing so I can't rellay help you on that.
However a Koa implementation goes as follows:
```es6
const app = new Koa();

const cacheMiddleware = async (context, next) => {
  context.state = context.state || {};
  context.state.cache = new Cache(orm);
  /* do all the stuff, they can access their own dedicated cache from context.state */
  await next();
  /* get rid of the cache (this is useless if context.state is unreachable after a request is done, but you can't be sure (e.g. middlewares storing context in global scope for some reason)) */
  delete context.state.cache;
}

app.use(cacheMiddleware)
```
Passing `context.state` to `graphql()`, you can access the cache from the resolvers.

A more agnostic way (yet equivalent) to do this is with a cache register
```es6
const cacheRegister = new Map();

export function summonCache(requestID) {
	if (!cacheRegister.has(requestID)) {
		cacheRegister.set(requestID, new Cache(orm));
	}
	return cacheRegister.get(requestID);
};

export function releaseCache(requestID) {
	return cacheRegister.delete(requestID);
};
```
So if you can access your `requestID` from somewhere in your app, you import `summonCache` and use it to get the cache. When your sending your request, you call `releaseCache` to get rid of it.

**Comment by jvallarvisp** [comment] 2016-12-15 02:59
I created a Pull Request. Can you review it #4

**Comment by mattecapu** [comment] 2016-12-15 20:03
Thank you for the contribution, I merged your PR

**Closed as completed by mattecapu** 2016-12-15 20:03 UTC
